(* ::Package:: *)

(************************************************************************)
(* This file was generated automatically by the Mathematica front end.  *)
(* It contains Initialization cells from a Notebook file, which         *)
(* typically will have the same name as this file except ending in      *)
(* ".nb" instead of ".m".                                               *)
(*                                                                      *)
(* This file is intended to be loaded into the Mathematica kernel using *)
(* the package loading commands Get or Needs.  Doing so is equivalent   *)
(* to using the Evaluate Initialization Cells menu command in the front *)
(* end.                                                                 *)
(*                                                                      *)
(* DO NOT EDIT THIS FILE.  This entire file is regenerated              *)
(* automatically each time the parent Notebook file is saved in the     *)
(* Mathematica front end.  Any changes you make to this file will be    *)
(* overwritten.                                                         *)
(************************************************************************)



BeginPackage["PowersOfTrig`"]


PowersOfTrig::usage = "The package PowersOfTrig` provides the functions,

UsePowersOfSin[\[Theta]]
UsePowersOfCos[\[Theta]]
UsePowersOfSinh[\[Theta]]
UsePowersOfCosh[\[Theta]]

where \[Theta] is the variable for which the transformations are to be automatically done.
The transformation rules that are set up by one of the above can be cleared by using
the corresponding ClearPowersOf...[ ]  function,

ClearPowersOfSin[\[Theta]]
ClearPowersOfCos[\[Theta]]
ClearPowersOfSinh[\[Theta]]
ClearPowersOfCosh[\[Theta]]

";


UsePowersOfSin::usage=PowersOfTrig::usage
UsePowersOfCos::usage=PowersOfTrig::usage
UsePowersOfSinh::usage=PowersOfTrig::usage
UsePowersOfCosh::usage=PowersOfTrig::usage
ClearPowersOfSin::usage=PowersOfTrig::usage
ClearPowersOfCos::usage=PowersOfTrig::usage
ClearPowersOfSinh::usage=PowersOfTrig::usage
ClearPowersOfCosh::usage=PowersOfTrig::usage


Begin["`Private`"]


UsePowersOfSin[x_]:=(Unprotect[Power];
Cos[x]^2=1-Sin[x]^2;
Cos[x]^n_/;n>2:=Expand[( 1-Sin[x]^2)Cos[x]^(n-2)];
Protect[Power];)


UsePowersOfCos[x_]:=(Unprotect[Power];
Sin[x]^2=1-Cos[x]^2;
Sin[x]^n_/;n>2:=Expand[( 1-Cos[x]^2)Sin[x]^(n-2)];
Protect[Power];)


UsePowersOfSinh[x_]:=(Unprotect[Power];
Cosh[x]^2=1+Sinh[x]^2;
Cosh[x]^n_/;n>2:=Expand[( 1+Sinh[x]^2)Cosh[x]^(n-2)];
Protect[Power];)


UsePowersOfCosh[x_]:=(Unprotect[Power];
Sinh[x]^2=Cosh[x]^2 - 1;
Sinh[x]^n_/;n>2:=Expand[(Cosh[x]^2 - 1)Sinh[x]^(n-2)];
Protect[Power];)


End[]


EndPackage[]
