(* ::Package:: *)

(************************************************************************)
(* This file was generated automatically by the Mathematica front end.  *)
(* It contains Initialization cells from a Notebook file, which         *)
(* typically will have the same name as this file except ending in      *)
(* ".nb" instead of ".m".                                               *)
(*                                                                      *)
(* This file is intended to be loaded into the Mathematica kernel using *)
(* the package loading commands Get or Needs.  Doing so is equivalent   *)
(* to using the Evaluate Initialization Cells menu command in the front *)
(* end.                                                                 *)
(*                                                                      *)
(* DO NOT EDIT THIS FILE.  This entire file is regenerated              *)
(* automatically each time the parent Notebook file is saved in the     *)
(* Mathematica front end.  Any changes you make to this file will be    *)
(* overwritten.                                                         *)
(************************************************************************)



(* ::Input::Initialization:: *)
BeginPackage["NotebookEvaluation`"]


(* ::Input::Initialization:: *)
NotebookEvaluation::usage="This package provides the functions:  EvaluateStopsHere\[VeryThinSpace],  EvaluateUntilHere  and  CPUTimeUntilHere"


(* ::Input::Initialization:: *)
EvaluateStopsHere::usage="EvaluateStopsHere\[VeryThinSpace][ ]  returns Null. It doesn't normally do anything, but if you do  \"Evaluation \[Rule] Evaluate Notebook\"  from the menu,
then the evaluation of the notebook will stop at this statement.

Similarly, this statement will stop evaluation of a selection, initiated by selecting with the mouse and then doing Shift+Enter." ;


(* ::Input::Initialization:: *)
EvaluateUntilHere::usage="EvaluateUntilHere\[VeryThinSpace][ ] returns Null.  It will cause the notebook to be evaluated as if   \"Evaluation \[Rule] Evaluate Notebook\"  had been chosen from the menu,
but the evaluation will stop at the place where this statement is evaluated.

EvaluateUntilHere\[VeryThinSpace][\[VeryThinSpace]pre, post\[VeryThinSpace]]   will execute pre, then evaluate all cells until here, then evaluate post.

For example, this is the definition of the function  CPUTimeUntilHere\[VeryThinSpace][ ]\[VeryThinSpace],

CPUTimeUntilHere[ ] := 
  EvaluateUntilHere[                      
    ClearSystemCache[ ] ;
    $TimeUsedStart = TimeUsed[ ]
    ,                
    $TimeUsedEnd=TimeUsed[ ] ;                   
    $TimeUsedEnd-$TimeUsedStart                        
  ]";


(* ::Input::Initialization:: *)
Begin["`Private`"]


(* ::Input::Initialization:: *)
EvaluateStopsHere[]:=CheckAbort[FrontEndTokenExecute["EvaluatorAbort"] ,Null]


(* ::Input::Initialization:: *)
SetAttributes[EvaluateUntilHere,HoldAll];
EvaluateUntilHere[]:=EvaluateUntilHere[Null,Null]
EvaluateUntilHere[pre_,post_]:=CheckAbort[If[TrueQ[$UpToHere],
$UpToHere=False;
SelectionMove[EvaluationNotebook[],Before,GeneratedCell];
SelectionMove[EvaluationNotebook[],Previous,Cell];
SelectionMove[EvaluationNotebook[],Before,Cell];
CheckAbort[FrontEndTokenExecute["EvaluatorAbort"],Null];
Pause[1];
CheckAbort[Abort[],post]
,
$UpToHere=True;
pre;
FrontEndTokenExecute["SelectAll"];
FrontEndTokenExecute["EvaluateCells"]],post]


(* ::Input::Initialization:: *)
CPUTimeUntilHere[]:= EvaluateUntilHere[
ClearSystemCache[];$TimeUsedStart=TimeUsed[],
$TimeUsedEnd=TimeUsed[];$TimeUsedEnd-$TimeUsedStart]


(* ::Input::Initialization:: *)
End[]
EndPackage[]
