(* ::Package:: *)

(************************************************************************)
(* This file was generated automatically by the Mathematica front end.  *)
(* It contains Initialization cells from a Notebook file, which         *)
(* typically will have the same name as this file except ending in      *)
(* ".nb" instead of ".m".                                               *)
(*                                                                      *)
(* This file is intended to be loaded into the Mathematica kernel using *)
(* the package loading commands Get or Needs.  Doing so is equivalent   *)
(* to using the Evaluate Initialization Cells menu command in the front *)
(* end.                                                                 *)
(*                                                                      *)
(* DO NOT EDIT THIS FILE.  This entire file is regenerated              *)
(* automatically each time the parent Notebook file is saved in the     *)
(* Mathematica front end.  Any changes you make to this file will be    *)
(* overwritten.                                                         *)
(************************************************************************)



(* ::Input::Initialization:: *)
Needs["Backup`"]
DeleteLockFile[ ]
StartBackup[] 
Get["TeXit`"] 


(* ::Input::Initialization:: *)
TeXit["abc $ def"]


(* ::Input::Initialization:: *)
(InputTeXit[];NotebookDelete[EvaluationCell[]];)


(* ::Input::Initialization:: *)
\[Iota]s:=(TeXitSection[InputFontSize->20,InputFontFamily->"Helvetica"];NotebookDelete[EvaluationCell[]];)


(* ::Input::Initialization:: *)
\[Iota]s:=(TeXitSection[InputFontSize->18];NotebookDelete[EvaluationCell[]];)


(* ::Input::Initialization:: *)
\[Iota]s:=(TeXitSection[];NotebookDelete[EvaluationCell[]];)


(* ::Input::Initialization:: *)
Apply[Sequence,Options[TeXitSection]]


(* ::Input::Initialization:: *)
Options[TeXitSection]={
InputBackground->{242,242,242},
InputFontSize->19,
InputCellFrame->False,
InputShowGroupOpener->True, 
InputCellMargins->{{66,2},{2,2}}
};


(* ::InheritFromParent::Initialization::DemiBold:: *)
Cell[StyleData["Code"],
 PageWidth->Infinity,
 CellMargins->{{66, 10}, {10, 10}},
 Evaluatable->True,
 CellGroupingRules->"InputGrouping",
 TextClipboardType->"Package",
 StripStyleOnPaste->True,
 CellHorizontalScrolling->True,
 PageBreakWithin->False,
 GroupPageBreakWithin->False,
 InitializationCell->True,
 DefaultFormatType->DefaultInputFormatType,
 AutoIndent->True,
 ContextMenu->FEPrivate`FrontEndResource["ContextMenus", "Input"],
 ShowAutoStyles->True,
 ShowPredictiveInterface->False,
 HyphenationOptions->{"HyphenationCharacter"->"\[Continuation]"},
 AutoItalicWords->{},
 AutoQuoteCharacters->{},
 PasteAutoQuoteCharacters->{},
 LanguageCategory->"Input",
 AutoSpacing->False,
 ShowStringCharacters->True,
 NumberMarks->True,
 DigitBlock->Infinity,
 ZeroWidthTimes->True,
 LineBreakWithin->False,
 LineIndent->0,
 CounterIncrements->"Code",
 MenuSortingValue->1450,
 MenuCommandKey->"8",
 FontWeight->"DemiBold"]


(* ::InheritFromParent::Initialization::DemiBold:: *)
StyleData["mycell"]



