(* ::Package:: *)

(************************************************************************)
(* This file was generated automatically by the Mathematica front end.  *)
(* It contains Initialization cells from a Notebook file, which         *)
(* typically will have the same name as this file except ending in      *)
(* ".nb" instead of ".m".                                               *)
(*                                                                      *)
(* This file is intended to be loaded into the Mathematica kernel using *)
(* the package loading commands Get or Needs.  Doing so is equivalent   *)
(* to using the Evaluate Initialization Cells menu command in the front *)
(* end.                                                                 *)
(*                                                                      *)
(* DO NOT EDIT THIS FILE.  This entire file is regenerated              *)
(* automatically each time the parent Notebook file is saved in the     *)
(* Mathematica front end.  Any changes you make to this file will be    *)
(* overwritten.                                                         *)
(************************************************************************)



(* ::Input::Initialization:: *)
If[TrueQ[$tpTensorEditMode],
$tpTensorDirectory=Directory[],
$tpTensorDirectory=DirectoryName[$InputFileName]]


(* ::Input::Initialization:: *)
$tpTensorVersion=Last[FileNameSplit[$tpTensorDirectory]]


(* ::Input::Initialization:: *)
If[StringContainsQ[$System,"Linux"],
Needs["ShortWindowTitles`"]]


(* ::Input::Initialization:: *)
NBFilePart={
"Part0--Setup_and_usage_docs.nb",
"Part1--Declarations_and_basic_fns.nb",
"Part2--Gradient_series_and_metric.nb",
"Part3--Tensor_symmetries_and_standard_forms.nb",
"Part4--Differential_geometry.nb",
"Part5--EqnNumbers.nb",
"Part6--Canonicalization.nb",
"PartX--Last_section.nb"
};



(* ::Input::Initialization:: *)
NBPartMax = Length[NBFilePart];


(* ::Input::Initialization:: *)
If[$tpTensorEditMode,
Table[NBObjPart[j]=NotebookOpen[FileNameJoin[{$tpTensorDirectory,NBFilePart[[j]]}]],{j,1,NBPartMax}]//Column ];


(* ::Input::Initialization:: *)
Needs["Backup`"]


(* ::Input::Initialization:: *)
If[$tpTensorEditMode,DeleteFile[FileNames["Locked",FileNames["*_bak"]]];StartBackup[]]
If[$tpTensorEditMode,Table[{NBFilePart[[j]],"-",StartBackup[NBObjPart[j]]},{j,1,NBPartMax}]//TableForm]


(* ::Input::Initialization:: *)
$InitializationTimes={};
$InitializationTimeZero = AbsoluteTime[];

SaveInitTime[]:=(
AppendTo[$InitializationTimes,{FileBaseName[NotebookFileName[]],AbsoluteTime[]-$InitializationTimeZero}];
$InitializationTimeZero = AbsoluteTime[];)

InitTimes[]:= $InitializationTimes//Table
TotalInitTime[]:=Total[Map[#[[2]]&,$InitializationTimes]]



(* ::Input::Initialization:: *)
$PrintDebugLocation=False;
If[TrueQ[$PrintDebugLocation],Print["In tpTensor.nb"]]



(* ::Input::Initialization:: *)
If[$tpTensorEditMode,
Do[
FrontEndExecute[FrontEndToken[NBObjPart[j],"EvaluateInitialization"]],
{j,1,NBPartMax}]]



(* ::Input::Initialization:: *)
If[$tpTensorEditMode,1+2]


(* ::Input::Initialization:: *)
If[!TrueQ[$tpTensorEditMode],
NBFileGets =Table[Get[FileNameJoin[{$tpTensorDirectory,FileBaseName[NBFilePart[[j]]]<>".m"}]],{j,1,NBPartMax}];
If[!Apply[And,Map[SameQ[#,Null]&,NBFileGets]],NBFileGets]]


(* ::Input::Initialization:: *)
CopyrightStatement=OpenerView[{" tpTensor "<>$tpTensorVersion<>": A package for index-free tensor algebra."<>"
 Copyright \[Copyright] 2015 Andrew H. Norton.
 \[VeryThinSpace]Released under GPLv3 or later.",{"
    tpTensor is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.
  
    tpTensor is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.
  
    You should have received a copy of the GNU General Public License
    along with tpTensor. If not, see ",Hyperlink["http://www.gnu.org/licenses/"],"."}//Row}]
