(* ::Package:: *)

(************************************************************************)
(* This file was generated automatically by the Mathematica front end.  *)
(* It contains Initialization cells from a Notebook file, which         *)
(* typically will have the same name as this file except ending in      *)
(* ".nb" instead of ".m".                                               *)
(*                                                                      *)
(* This file is intended to be loaded into the Mathematica kernel using *)
(* the package loading commands Get or Needs.  Doing so is equivalent   *)
(* to using the Evaluate Initialization Cells menu command in the front *)
(* end.                                                                 *)
(*                                                                      *)
(* DO NOT EDIT THIS FILE.  This entire file is regenerated              *)
(* automatically each time the parent Notebook file is saved in the     *)
(* Mathematica front end.  Any changes you make to this file will be    *)
(* overwritten.                                                         *)
(************************************************************************)



BeginPackage["SumsOfAngle`"]


SumsOfAngle::usage="The package  SumsOfAngle  will transform products of Sin[\[Theta]] and Cos[\[Theta]] into sums of Sin[m\[Theta]] and Cos[m\[Theta]], 
thus automatically calculating Fourier series. The functions provided are :

UseSumsOfAngle[\[Theta]]

ClearSumsOfAngle[\[Theta]]

where \[Theta] is a specified angular variable." 


UseSumsOfAngle::usage=SumsOfAngle::usage


ClearSumsOfAngle::usage=SumsOfAngle::usage


Begin["`Private`"]


Clear[UseSumsOfAngle]
UseSumsOfAngle[x_] := (
Unprotect[Sin,Cos,Power];
Sin[x] Cos[x] ^= 1/2 Sin[2x];
Sin/:Sin[x]^2=1/2(1-Cos[2 x]);
Cos/:Cos[x]^2=1/2(1+Cos[2 x]);
Sin[x]^n_ /; n>2 ^:= Expand[1/2(1-Cos[2 x]) Sin[x]^(n-2)];
Cos[x]^n_ /; n>2 ^:= Expand[1/2(1+Cos[2 x]) Cos[x]^(n-2)];
Sin[x] Sin[n_ x]^:=1/2 Cos[(1-n)x]-1/2 Cos[(1+n) x];
Cos[x] Cos[n_ x]^:=1/2 Cos[(1-n) x]+1/2 Cos[(1+n) x];
Cos[x] Sin[n_ x]^:=1/2 Sin[(1+n) x]-1/2 Sin[(1-n) x];
Sin[x] Cos[n_ x]^:=1/2 Sin[(1+n) x]-1/2 Sin[(n-1) x];
Sin[m_ x] Sin[n_ x]^:=1/2 Cos[(m-n) x]-1/2 Cos[(m+n) x];
Cos[m_ x] Cos[n_ x]^:=1/2 Cos[(m-n) x]+1/2 Cos[(m+n) x];
Cos[m_ x] Sin[n_ x]^:=1/2 Sin[(m+n) x]-1/2 Sin[(m-n) x];
Sin/:Sin[m_ x]^2:=1/2(1-Cos[2 m x]);
Cos/:Cos[m_ x]^2:=1/2(1+Cos[2 m x]);
Sin/:Sin[m_ x]^n_ /; n>2 := Expand[1/2(1-Cos[2m x]) Sin[m x]^(n-2)];
Cos/:Cos[m_ x]^n_ /; n>2 := Expand[1/2(1+Cos[2 m x]) Cos[m x]^(n-2)];
Protect[Sin,Cos,Power];)


Clear[ClearSumsOfAngle]
ClearSumsOfAngle[x_] := (
Unprotect[Sin,Cos,Power];
Sin /:Sin[x] Cos[x] =.;
Cos /:Sin[x] Cos[x] =.;
Sin /: Sin[x]^2=.;
Cos /: Cos[x]^2=.;
Sin/:Sin[x]^n_ /; n>2 =.;
Cos /:Cos[x]^n_ /; n>2 =.;
Sin /: Sin[x] Sin[n_ x]=.;
Cos /: Cos[x] Cos[n_ x]=.;
Sin /: Cos[x] Sin[n_ x]=.;
Sin /: Sin[x] Cos[n_ x]=.;
Cos /: Cos[x] Sin[n_ x]=.;
Cos /: Sin[x] Cos[n_ x]=.;
Sin /: Sin[m_ x] Sin[n_ x]=.;
Cos /: Cos[m_ x] Cos[n_ x]=.;
Sin /: Cos[m_ x] Sin[n_ x]=.;
Cos /: Cos[m_ x] Sin[n_ x]=.;
Sin /: Sin[m_ x]^2=.;
Cos /: Cos[m_ x]^2=.;
Sin /: Sin[m_ x]^n_ /; n>2 =.;
Cos /: Cos[m_ x]^n_ /; n>2 =.;
Protect[Sin,Cos,Power];)


End[]


EndPackage[]
