(* ::Package:: *)

(************************************************************************)
(* This file was generated automatically by the Mathematica front end.  *)
(* It contains Initialization cells from a Notebook file, which         *)
(* typically will have the same name as this file except ending in      *)
(* ".nb" instead of ".m".                                               *)
(*                                                                      *)
(* This file is intended to be loaded into the Mathematica kernel using *)
(* the package loading commands Get or Needs.  Doing so is equivalent   *)
(* to using the Evaluate Initialization Cells menu command in the front *)
(* end.                                                                 *)
(*                                                                      *)
(* DO NOT EDIT THIS FILE.  This entire file is regenerated              *)
(* automatically each time the parent Notebook file is saved in the     *)
(* Mathematica front end.  Any changes you make to this file will be    *)
(* overwritten.                                                         *)
(************************************************************************)



BeginPackage["ShortWindowTitles`"]


ShortWindowTitlesUsage="
StartShortWindowTitles[ ]   will remove the text  \"Wolfram Mathematica...\"  from window titles (if it exists), replacing
these titles with shortened versions, typically a  .nb  file name.  This is to clean up certain Linux desktop environments.

The KDE desktop insists on appending application names to window titles. These names also appear in the 
window pager and taskbar entries, and are just background noise. There may be nicer ways to set window titles 
on other desktops, but on KDE this can be difficult.

A task running each 0.5 sec reads the titles of all windows on the desktop and modifies the titles of any 
Mathematica windows as required. This is an ongoing task because whenever an un-modified notebook is 
edited the original long title is re-displayed with  \"*\"  appended to the file name to indicate modification.
Thus, window titles needs to be re-set frequently.

This program will only run on Linux. It has only been tested on Debian running the KDE desktop,
but it should work for any EWMH/NetWM compatible X Window Manager. See: man wmctrl
 
This program requires that the Linux package \"wmctrl\" be installed. 

StartShortWindowTitles[ ]  is run automatically after  Needs[ \"ShortWindowTitles`\" ] ,  so is only required
for re-start the task.

StopShortWindowTitles[ ]  will remove the task started by  StartShortWindowTitles[ ] ." ;
ShortWindowTitles::usage = ShortWindowTitlesUsage;
StartShortWindowTitles::usage = ShortWindowTitlesUsage;
StopShortWindowTitles::usage = ShortWindowTitlesUsage;


Begin["`Private`"];


ReadFile[f_String]:=Module[{char,stream,string},
string="";
stream=OpenRead[f];
char=Read[stream,Character];
While[!char===EndOfFile,
string=string<>char;
char=Read[stream,Character]];
Close[stream];
string]


ShortTitleTask:=(
Run["/usr/bin/wmctrl -l > /tmp/WindowTitleInfo.tmp"];
s0=ReadFile["/tmp/WindowTitleInfo.tmp"];
s1=StringSplit[s0,"\n"];
s2=StringCases[s1,x__~~" - Wolfram Mathematica"~~___:>x];
s3 = Flatten[DeleteCases[s2,{}]];
s4=Map[StringSplit[#]&,s3];
s5=Map[Drop[#,3]&,s4];
s6=Map[StringJoin[#," "]&,s5,{2}];
s7=Map[StringJoin,s6];
s8=Map[If[!(StringContainsQ[#,".nb"]||StringContainsQ[#,"Untitled-"]||#==="Messages "), "Ref - "<>#,#]& ,s7] ;
w=Map[First,s4];
Do[
Run["/usr/bin/wmctrl -F -i -r "<>w[[j]]<>" -T '"<>s8[[j]]<>"'"],
{j,Length[w]}];)


StartShortWindowTitles[]:=RunScheduledTask[ShortTitleTask,0.5]; 
StopShortWindowTitles[]:=Quiet[RemoveScheduledTask[RunShortTitleTask]];   


StartShortWindowTitles[];


End[];
EndPackage[];



