(* ::Package:: *)

(************************************************************************)
(* This file was generated automatically by the Mathematica front end.  *)
(* It contains Initialization cells from a Notebook file, which         *)
(* typically will have the same name as this file except ending in      *)
(* ".nb" instead of ".m".                                               *)
(*                                                                      *)
(* This file is intended to be loaded into the Mathematica kernel using *)
(* the package loading commands Get or Needs.  Doing so is equivalent   *)
(* to using the Evaluate Initialization Cells menu command in the front *)
(* end.                                                                 *)
(*                                                                      *)
(* DO NOT EDIT THIS FILE.  This entire file is regenerated              *)
(* automatically each time the parent Notebook file is saved in the     *)
(* Mathematica front end.  Any changes you make to this file will be    *)
(* overwritten.                                                         *)
(************************************************************************)



(* ::Input::Initialization:: *)
CustomTeX[cmB,"{cm}_{{}_{\\rm B}}"]
CustomTeX[qB,"{q}_{{}_{\\rm B}}"]
CustomTeX[\[Lambda]B,"{\\lambda}_{{}_{\\rm B}}"]
CustomTeX[fRad,"f_{\\rm rad}"]
CustomTeX[hRad,"h_{\\rm rad}"]
CustomTeX[\[GothicCapitalD][z],"\\dot z "]
CustomTeX[\[GothicCapitalD][z,2],"\\ddot z "]
CustomTeX[\[GothicCapitalD][z,3],"z^{{}^{(3)}}"]
CustomTeX[\[GothicCapitalD][z,3],"\\overset{{}^{(3)}}{z}"]
CustomTeX[\[GothicCapitalD][z,3],"z^{\\!\\!\\!\\!\\!{}^{(3)}}"]
CustomTeX[\[GothicCapitalD][z,4],"z^{\\!\\!\\!\\!\\!{}^{(4)}}"]


(* ::Input::Initialization:: *)
CustomTeX[pEuler,"\\mathcal{E}_{p}"]
CustomTeX[\[Sigma]Euler,"\\mathcal{E}_{\\sigma}"]


(* ::Input::Initialization:: *)
Null
