(* ::Package:: *)

(************************************************************************)
(* This file was generated automatically by the Mathematica front end.  *)
(* It contains Initialization cells from a Notebook file, which         *)
(* typically will have the same name as this file except ending in      *)
(* ".nb" instead of ".m".                                               *)
(*                                                                      *)
(* This file is intended to be loaded into the Mathematica kernel using *)
(* the package loading commands Get or Needs.  Doing so is equivalent   *)
(* to using the Evaluate Initialization Cells menu command in the front *)
(* end.                                                                 *)
(*                                                                      *)
(* DO NOT EDIT THIS FILE.  This entire file is regenerated              *)
(* automatically each time the parent Notebook file is saved in the     *)
(* Mathematica front end.  Any changes you make to this file will be    *)
(* overwritten.                                                         *)
(************************************************************************)



(* ::Input::Initialization:: *)
DirectoryTree[]:=Module[{s1,s2,s3, subs},
subs={"\[CapitalATilde]"->"|","\[CapitalADoubleDot]"->"  ","\.b3"->"|","\[CapitalAGrave]"->"|"};
s1=StringReplace[RunProcess[{"tree","-Sd"},"StandardOutput"],subs];
s2=StringReplace[s1,{"|  "->"  |"}];
s3=StringReplace[s2,{"\n  "->"\n","\n|  "->"\n|"}]
]


(* ::Input::Initialization:: *)
FileTree[]:=Module[{s1,s2,s3, subs},
subs={"\[CapitalATilde]"->"|","\[CapitalADoubleDot]"->"  ","\.b3"->"|","\[CapitalAGrave]"->"|"};
s1=StringReplace[RunProcess[{"tree","-S"},"StandardOutput"],subs];
s2=StringReplace[s1,{"|  "->"  |"}];
s3=StringReplace[s2,{"\n  "->"\n","\n|  "->"\n|"}]
]



