(* ::Package:: *)

(************************************************************************)
(* This file was generated automatically by the Mathematica front end.  *)
(* It contains Initialization cells from a Notebook file, which         *)
(* typically will have the same name as this file except ending in      *)
(* ".nb" instead of ".m".                                               *)
(*                                                                      *)
(* This file is intended to be loaded into the Mathematica kernel using *)
(* the package loading commands Get or Needs.  Doing so is equivalent   *)
(* to using the Evaluate Initialization Cells menu command in the front *)
(* end.                                                                 *)
(*                                                                      *)
(* DO NOT EDIT THIS FILE.  This entire file is regenerated              *)
(* automatically each time the parent Notebook file is saved in the     *)
(* Mathematica front end.  Any changes you make to this file will be    *)
(* overwritten.                                                         *)
(************************************************************************)



(* ::Input::Initialization:: *)
pDValues[X___]:=Map[(Apply[HoldForm[pD],Most[#]]==Last[#])&,pDData[X]]


(* ::Input::Initialization:: *)
SetpD[X_,a__,val_]:=Module[{b},
b=SortBy[{a},pDIndex];
ToExpression[RowBox[{"pD[",X,",","c$__] /; ContainsAll[{c$},",ToBoxes[b],"]:=pD[",MakeBoxes[val],",","Apply[Sequence,DeleteElements[{c$},",ToBoxes[b],"]]]"}]];
pDData[X]=Append[DeleteCases[pDData[X],Append[b,_]],Append[b,val]];
val
]



